# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a7896834b5959099c9c905d6e57fd5136c9a11e328ddc5bbcd17030f959cf1be513e92d2bc5116d083213b7cf6249e5ac0699e79979c7d0ae3efef5500478d9

test:
  secret_key_base: d38afe317bca0dac73dc52cda0aa64bacc78327ab4a5f6c33415146dc04514d43d7ec159cbe933534d38c11da7dfd67de8615160c59dec9ae6721ed2b13eb7b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
